#name: Auto-merge Dependabot PRs
#
#on:
#  pull_request:
#    types: [opened, synchronize, reopened, labeled, unlabeled]
#
#permissions:
#  contents: read
#  issues: write
#  checks: write
#  pull-requests: write
#
#jobs:
#  auto-merge:
#    runs-on: ubuntu-latest
#    if: contains(github.event.pull_request.labels.*.name, 'dependencies') && !github.event.pull_request.draft
#    steps:
#      - name: Wait for tests to succeed
#        uses: lewagon/wait-on-check-action@v1.3.1
#        with:
#          ref: ${{ github.event.pull_request.head.sha }}
#          check-name: 'build-and-test'
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          wait-interval: 10
#
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#        with:
#          token: ${{ secrets.OZGEN_BOT_TOKEN }}
#
#      - name: Add 'calendar release' label to PR
#        run: gh pr edit "$PR_NUMBER" --add-label "calendar release"
#        env:
#          GH_TOKEN: ${{ secrets.OZGEN_BOT_TOKEN }}
#          PR_NUMBER: ${{ github.event.pull_request.number }}
#
#      - name: Auto-merge PR if CI checks are successful
#        uses: actions/github-script@v4
#        with:
#          script: |
#            github.pulls.merge({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              pull_number: context.issue.number
#            })
#          github-token: ${{secrets.OZGEN_BOT_TOKEN}}
